@baseUrl = http://localhost:5000
@urlPath = api/v1/clinic

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "test26",
  "password": "test26",
  "email": "test26@gmail.com"

}
###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true
{
   "email":"test26@gmail.com",
   "password":"test26"
}

###
GET {{baseUrl}}/{{urlPath}}/currentUser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/getAuthData
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/updateauth
Content-Type: application/json
Accept: application/json
withCredentials: true
{
	"email":"test26updated@gmail.com",
	"username":"test22updated"
}
###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/deleteClinic
Content-Type: application/json
Accept: application/json
withCredentials: true
###

